apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-binding
  namespace: final
subjects:
  - kind: ServiceAccount
    name: clo835-group6
    namespace: final
roleRef:
  kind: Role
  name: clo835-group6
  apiGroup: rbac.authorization.k8s.io