apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp
data:
  DBHOST: "mysql"
  DBPORT: "3306"
  GROUP_NAME: "GROUP6"
  DBUSER: "root"
  IMAGE_URL: "https://arman-finalproject.s3.us-east-1.amazonaws.com/image1.jpg"
 