---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: cGFzczEyMw== # base64 encoded password
  mysql-database: ZW1wbG95ZWVz   # base64 encoded database name
  username: cm9vdA==  # base64 encoded "root"
  password: cGFzczEyMw== # base64 encoded "password"
